### ISSUE TITLE
Choose where to save the txt file on Mac

### ISSUE THREAD

**Issue by LuceCarter** [jamesmontemagno/MyStreamTimer#13]
I just went to try this out with OBS on Mac. The location of the txt file is buried in ~/Library/Containers.. which is hard to find from OBS as Library is hidden.
Is it possible to either default to an easier location or allow the user to choose a location easier to get to?

**Comment by jamesmontemagno** [comment]
You should be able to hit the copy button in there and then paste that into OBS. 

Could let people choose I guess.... wouldn't be the worst idea :)

**Comment by LuceCarter** [comment]
It may well be user error on my part but for me, when I click the box for the file location it doesn't let me paste anything only browse to the location and obviously MacOS doesn't have an easy way to paste a file path in Finder like you can Windows Explorer.

**Comment by jamesmontemagno** [comment]
so, yeah this is super tricky..

When the dialog comes up hit CMD + SHIFT + G can you can paste it in. I should put that somewhere in the app i guess :)

**Comment by jamesmontemagno** [comment]
Put it in the readme :)
