### ISSUE TITLE
Stream Deck can't access mystreamtimer:// as of recent windows updates

### ISSUE THREAD

**Issue by MYCRAFTisbest** [jamesmontemagno/MyStreamTimer#17]
Stream Deck launch strings like mystreamtimer://countdown/?mins=6 no longer work with the latest version of windows. Instead a yellow triangle with an exclamation point appears and the application claims that it can't access that location.

It could have been a stream deck update, but I'm fairly certain this issue happened a little over a week ago with the new Windows 10 update.
![mystrtimerror](https://user-images.githubusercontent.com/2159240/69502638-6c8e9180-0edf-11ea-933a-b38e1430edc6.png)

**Comment by aussieqgaming** [comment]
I have the same issue

**Comment by jamesmontemagno** [comment]
Hey there! Sorry, I was out of town. 

They changed Stream Deck :( All you have to do is switch to use "System -> Website"
