### ISSUE TITLE
remote launching

### ISSUE THREAD

**Issue by saitoh183** [jamesmontemagno/MyStreamTimer#21]
@jamesmontemagno 

I wanted to know if it would be possible to launch 
`mystreamtimer://countdown/?mins=10` on a remote machine? I have a 2 pc stream setup and i use TouchPortal. I wanted to run touchportal from my gaming pc but i cant run MyST from my gaming pc because it will interfere with fullscreen. When i press BRB button in TouchPortal, i have it switch to my brb screen in obs and then launch `mystreamtimer://countdown/?mins=10`. This works fine when im running it off the streaming pc but i want to move TouchPortal to my gaming pc so that i can control other stuff. My only issue is MyST.

I have tried scripting in python using a url launcher but it didnt work. I also tried using powershell to launch the MyST app but it cant launch `mystreamtimer://countdown/?mins=10`

Maybe you have an idea?

**Comment by jamesmontemagno** [comment]
I don't think so, you could send a system command with it perhaps via powershell?

**Comment by LiQiuDGG** [comment]
@saitoh183  take a look at the my stream timer extension, you should be able to call that from your gaming PC to your streaming PC.

**Comment by jamesmontemagno** [comment]
Will close seeing @LiQiuDGG has a work around for it.
