### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by LiQiuDGG** [jamesmontemagno/MyStreamTimer#23]
On the latest build of windows, MyStreamTimer is constantly crashing.

I've pasted what I could find for logs on pastebin, let me know if I can test in any way.

Thanks.

https://pastebin.com/fCeVyKXV

**Comment by jamesmontemagno** [comment]
What version of windows are you on? If you run `winver` from your run menu?

**Comment by LiQiuDGG** [comment]
Newest release, Windows 10 Version 2004 (OS Build 19041.264)

**Comment by jamesmontemagno** [comment]
Hmmm don't have it yet will take a look though, probably just need to update to final version of .net core. interesting through.

**Comment by jamesmontemagno** [comment]
I am curious if installing the C++ redistributables will help out at all. I see a lot of people with this in other apps: https://answers.microsoft.com/en-us/windows/forum/all/error-message-when-attempting-to-run-origin/d517419e-7340-40f1-99fa-ab9602ed2c0d?tab=AllReplies#tabs

They are saying install x86 and x64 versions.

**Comment by LiQiuDGG** [comment]
I'll give that a try after I finish some other changes I'm, making.  Should be done by Wednesday.

**Comment by LiQiuDGG** [comment]
That fixed it.  Thank you very much.
