### ISSUE TITLE
Stream Deck not launching My Timer

### ISSUE THREAD

**Issue by LiQiuDGG** [jamesmontemagno/MyStreamTimer#24]
I have tested all 3 methods you suggest in the My Timer document, and none of the website links are working with Stream Deck.  If I run the same commands from the run menu of Windows it works fine.  I realize this is an issue with the Stream Deck and not an issue with your code, but when was the last time you tested on stream deck?  I'd just like to see if there is a version that is working with My Tiimer.

In the meantime I've just used the My Stream Timer Extension to give me command line access to the application.

**Comment by jamesmontemagno** [comment]
In Stream Deck you have to use the Website action:
![image](https://user-images.githubusercontent.com/1676321/83578908-b68aac80-a4ec-11ea-88dc-525f9c0e5865.png)

**Comment by LiQiuDGG** [comment]
That's what I was trying but it would never start the timer.

**Comment by jamesmontemagno** [comment]
Hmmm on Windows it launches the app, so the app has to be closed.

**Comment by LiQiuDGG** [comment]
It works fine from windows, it just doesn't work from the stream deck in windows.  I use exactly what you have in your screenshot above, and it does not start up the timer.

**Comment by jamesmontemagno** [comment]
strange, it does seem to work for me here.... screenshot me the streamdeck?

**Comment by LiQiuDGG** [comment]
Because such is the life of setting up a new stream, now it's working.  Sorry, and thank you for the help.
