### ISSUE TITLE
Feature Request: Close when timer finishes

### ISSUE THREAD

**Issue by LiQiuDGG** [jamesmontemagno/MyStreamTimer#25]
I'm using two timers.  One to countdown when I'm going to go live, and a second for when I take a 5 minute break during stream.  I've noticed that if I don't close the timer after my go live timer, I can't start my 5 minute timer when I go on a break.  Is there a way to either close the timer at the end, or allow the new passed command to supersede the previous command (IE a 5 minute command would start a 5 minute timer even if you started with a top of hour timer).

Let me know if that doesn't make sense, I realize this might be an edge case, but wanted to submit it as a feature request.

Thanks.

**Comment by jamesmontemagno** [comment]
Ah yeah that is a good idea. You can actually pass a command again on macOS, but I hadn't figured it out on Windows. Auto clos is a pretty good idea though.

**Comment by jamesmontemagno** [comment]
next version on windows will allow launching and updating the timer to a new time.

**Comment by jamesmontemagno** [comment]
Closing as the latest version allows for the specific request
