### ISSUE TITLE
Glitchy and laggy stream with timer running

### ISSUE THREAD

**Issue by KoughPhEE** [jamesmontemagno/MyStreamTimer#26]
Just wondering if there are fixes or reasons for the glitchy and laggy stream with MyStreamTimer running? I have 0 frames dropped while streaming with OBS yet it lags for that millisecond everytime MyStreamTimer writes a file (I suspect).

**Comment by jamesmontemagno** [comment]
Is this on windows? I have seen this a bit, but it hasn't been too bad. I have an update coming that cleans this up a bit that I just rolled out for macOS

**Comment by KoughPhEE** [comment]
This is on a new windows machine I built and was just setting up OBS when I noticed the choppiness. I turned closed down myStreamTimer and the problem goes away immediately. I will try on my mac to see if it is better. But Mac OBS doesn't seem to handle nested scenes very well which is why I am only on a PC when streaming... Thanks for the note back, I look foward to the update.
