### ISSUE TITLE
Feature requests: Allow Seconds and Read Time From MP3

### ISSUE THREAD

**Issue by bbakersc** [jamesmontemagno/MyStreamTimer#27]
For those of us streamers that have a startup tune, it would be great to also allow seconds to be defined for the length of the timer.

Also, another option would be to pass it the path to an MP3 file, have the app determine the duration of the MP3 from the metadata, set the timer to that length, and have the timer start.

**Comment by jamesmontemagno** [comment]
I do have seconds and a specific start time selection coming to Windows :)  

It is currently out on macOS
