### ISSUE TITLE
mystreamtimer://countdown/?to=15:30 only works if application is not open

### ISSUE THREAD

**Issue by isctylr** [jamesmontemagno/MyStreamTimer#28]
on UWP, if the application is already open, calling the command does nothing. If it's closed, it works as expected. I'm hoping to automate the beginning of a countdown, but I can't guarantee that the application will be open or closed when the command is called.

**Comment by jamesmontemagno** [comment]
correct, yeah you have to close it on Windows. I am looking into a way to make this happen like it does on macOS

**Comment by isctylr** [comment]
https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Activation.ProtocolActivatedEventArgs

**Comment by jamesmontemagno** [comment]
Yeah, it is a bit odd cause it is a WPF app actually in an MSIX container which is how I get protocals. So I don't have UWP apis. The protocol will open a new instance so i have to block that -> https://github.com/jamesmontemagno/MyStreamTimer/blob/master/MyStreamTimer.WPF/App.xaml.cs#L22 however, i think i can pass the info back to the original instance some how.

**Comment by isctylr** [comment]
Okay. (Thanks for talking me through this as I have no wpf experience.) So something like this probably isn't the right step then: https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/ ? I'll take a look at passing information between instances too.

**Comment by jamesmontemagno** [comment]
I may convert it over to UWP in the near future though and use Xamarin.Forms since I use that on macOS. I was using WPF on .NET Core 3 just to test some things out and use some nice styling. 

But yeah, may look at that and see if i can pass the info around. Thanks for the links!

**Comment by jamesmontemagno** [comment]
Have just implemented this in the next version! <3

**Comment by ralbright-wa** [comment]
Very interested in this next version. I am running this for a virtual conference and having it countdown to the top of the hour is a huge bonus. Thank you.
