### ISSUE TITLE
How to change MacOS App Name

### ISSUE THREAD

**Issue by baskren** [jamesmontemagno/MyStreamTimer#31]
I can see that you were able to set the MacOS App Name (as installed) via:

``` xml
 <AssemblyName>My Stream Timer</AssemblyName>
```

Which sounds like what I want to do as my app is getting rejected by Apple because the Assembly name is the same as the project name: `MyApp.Mac`.  I would like the app name to be "My App With Spaces" (just like yours).

However, when I modify the **<AssemblyName>** to have spaces(`<AssemblyName>My App Name With Spaces</AssemblyName>`), I get the following compilation errors:

```
clang : error : no such file or directory: 'App'
clang : error : no such file or directory: 'Name'
clang : error : no such file or directory: 'With'
clang : error : no such file or directory: 'Spaces.exe.dylib'
MMP : error MM3001: Could not AOT the assembly '/Users/benjaminaskren/Development/Xamarin/AssetBuilder/AssetBuilder.Mac/bin/Release/My App Name With Spaces.app/Contents/MonoBundle/My App Name With Spaces.exe'
    6 Warning(s)
    5 Error(s)
```

I've been digging through your project and I can't see how you did it.  So, how did you pull it off?

**Comment by jamesmontemagno** [comment]
I think you want your info.plist to be:

```
<key>CFBundleName</key>
<string>MyStreamTimer</string>
```

I just set the Window title to "My Stream Timer" -> https://github.com/jamesmontemagno/MyStreamTimer/blob/master/MyStreamTimer.Mac/AppDelegate.cs#L63

**Comment by jamesmontemagno** [comment]
I dont' AOT my mac app either though, but probably you want to make your Assembly name have no spaces

**Comment by baskren** [comment]
Bummer.  It appears that the **<AssemblyName>** is used for the name shown when you hover over the app's icon in the dock.  Apple isn't happy that it doesn't match what I've been using everywhere else (all the places you've mentioned).

**Comment by baskren** [comment]
@jamesmontemagno 

1. Why not AOT?

2. I was able to satisfy my need for spaces in the AssemblyName by replacing the ASCII spaces with Unicode **EN SPACE** (U+2000) spaces (copied and pasted from [here](https://en.wikipedia.org/wiki/Whitespace_character#Unicode)).

**Comment by jamesmontemagno** [comment]
Hmm that is odd...... Very interesting. I think I had issues with AOT for some reason and there really is no perf diff from what I saw on my machines. AOT was more important on phones.
