### ISSUE TITLE
[Feature Request] Countdown to specific time

### ISSUE THREAD

**Issue by XtoMHA96** [jamesmontemagno/MyStreamTimer#41]
Since Snaz has been discontinued, could these features be added to the application?

![imagen](https://user-images.githubusercontent.com/25475587/102080783-f10fc300-3e06-11eb-8fc8-b065e15688db.png)

**Comment by jamesmontemagno** [comment]
Yes, i have this in the next version. It is all staged and ready to go actually. I will push it out this week.

**Comment by dev-manager-uk** [comment]
Big ask, but any chance of this before NYE :-p

**Comment by jamesmontemagno** [comment]
It is published! AHHH, to get a midnight countdown, you will need to do 11:59 and then add 1 mintue after you start the countdown.

**Comment by dev-manager-uk** [comment]
Legend.  That works.  Thank you so much.  Awesome tool.  Sent you a few coffees!!  🥇

**Comment by jamesmontemagno** [comment]
Thank you so much!!! Hope you like the new update :)
