### ISSUE TITLE
Feature request: add more commands

### ISSUE THREAD

**Issue by exenza** [jamesmontemagno/MyStreamTimer#43]
I would love to interact with the app exclusively via streamdeck.

Would be then nice to have the following commands:

Add X minutes to the running countdown
mystreamtimer://countdown/?add=x
mystreamtimer://countdown/?remove=x
This will allow to create custom buttons in streamdeck to add and remove x amount of minutes

Start/Stop/Reset
mystreamtimer://countdown/?start
mystreamtimer://countdown/?stop
mystreamtimer://countdown/?reset

**Comment by MatzeJoerling** [comment]
Hi, i would also like to change "Live Output" and perhaps "Finish output" via command.

regards Martin

**Comment by Christolito** [comment]
+1 on having a command to add x minutes @jamesmontemagno

**Comment by jamesmontemagno** [comment]
I'll put these on my list for version 1.7
