### ISSUE TITLE
"Top of the hour" command is out by 1 minute

### ISSUE THREAD

**Issue by pokmot** [jamesmontemagno/MyStreamTimer#45]
Just downloaded it from MS Store - great software! Love it!

But... I am in Central European timezone, and when I use mystreamtimer://countdown/?topofhour it is out by one minute.

I have tried it several times and waited until I went past one hour to test again, and it is consistent.

![2021-01-29_18h59_33](https://user-images.githubusercontent.com/546113/106311324-41cb6600-6265-11eb-88ba-4fa1c5f2bdab.png)
![2021-01-29_19h03_55](https://user-images.githubusercontent.com/546113/106311343-4859dd80-6265-11eb-8202-817841098762.png)

**Comment by jamesmontemagno** [comment]
Very interesting.... I will take a look and try to get an update out. Thanks for reporting.

**Comment by jamesmontemagno** [comment]
Fixed up in the next release!
