### ISSUE TITLE
Please make standalone version for windows

### ISSUE THREAD

**Issue by kosirm** [jamesmontemagno/MyStreamTimer#52]
I have constant problems with Microsoft store (downloading errors), so could you please make standalone exe file for windows, please!

**Comment by jamesmontemagno** [comment]
Hmmmm that is odd. Could you create a new profile just to test out seeing if that is an issue?

You can download via App Center -> https://install.appcenter.ms/orgs/refractored-llc/apps/my-stream-timer/distribution_groups/public%20mystreamtimer
