### ISSUE TITLE
It says we can launch the timer using command line, how do we do this?

### ISSUE THREAD

**Issue by JoemerRamos** [jamesmontemagno/MyStreamTimer#54]
How do we do the issue in the title above?

**Comment by JoemerRamos** [comment]
![Screenshot 2021-05-18 133136](https://user-images.githubusercontent.com/34356209/118697623-7eec4180-b7dd-11eb-97e4-1b8cfa1a7368.png)

**Comment by jamesmontemagno** [comment]
yup, you can use those commands to launch my stream timer. Like on windows you can pass this command in to run or the browser:
![image](https://user-images.githubusercontent.com/1676321/118726144-c2e34480-b7e5-11eb-83e8-9b326bafe0e6.png)

Or if you are in command line you could say:

```
start mystreamtimer://countdown/?mins=6
```

**Comment by timboxyz** [comment]
What is the command-line form for OSX please?

**Comment by jamesmontemagno** [comment]
I am not a terminal expert, but if you go into "bash" you can then do:

open mystreamtimer://countdown/?mins=6
