### ISSUE TITLE
Choose Text Alignment

### ISSUE THREAD

**Issue by JavaShipped** [jamesmontemagno/MyStreamTimer#57]
Currently when the timer finishes, the text is aligned left. So if you have it positioned on the right side of the stream scene, the finish text is cut off as more characters are added.

Allowing the test to align right would mean the text gets 'pushed' left, rather then right when there is more characters.

![image](https://user-images.githubusercontent.com/29931954/126321280-38ec650b-42f8-4f03-9fb6-340890e3a877.png)

![image](https://user-images.githubusercontent.com/29931954/126321295-638e7713-6248-486a-a077-6103efaa9fbc.png)

Edit: Ignore this I legit forgot how OBS text works!

Edit: OBS's text align didn't actually do anything for this. So maybe not as dumb as I thought!

**Comment by jamesmontemagno** [comment]
So, what you want to do is set custom extents on the text view and force it to a specific size and then align it to the left/right
![image](https://user-images.githubusercontent.com/1676321/126410855-b86e7f7b-4147-481c-8bef-a6246c7ba9e4.png)
