### ISSUE TITLE
Countdown timer skips few numbers.

### ISSUE THREAD

**Issue by jeremiasmanninen** [jamesmontemagno/MyStreamTimer#60]
When using a countdown to a specific time some timecodes are skipped.
On a 2-minute countdown numbers (1:44 01:04,  00:07, 00:03, 00:02) where skipped. Another time numbers (1:44, 00:53, 00:02) were skipped. Sometimes it straight goes like from 00:04 to 00:02 in time of 1 second. Sometimes it freezes for 2 seconds like from 00:04 to 00:02.

I am using macOS Big Sur 11.6 on Mac Pro 5.1.

**Comment by jamesmontemagno** [comment]
it can be based on your machine and disk speed based on when OBS refreshes. We update the file every .75 seconds.

**Comment by jeremiasmanninen** [comment]
I am running on NVME SSD so the speed should not be a problem. What I looked at the thing closer I realized that on the MyStreamTimer app the countdown is perfect. But like on the 30 second cycles OBS begins to lose the time and when the lost time becomes 1 second it skips a number. I also tested changing my fancy font to Arial and taking of transparency effects but still the same problem.

Do you know how often OBS updates the text files? I guess it is 1 second (https://github.com/obsproject/obs-studio/pull/5023). would the problem be 0.75 seconds compared to the 1 second on OBS? 

Has anyone else had the same problem?

**Comment by jamesmontemagno** [comment]
Hmmm shouldnt' be an issue, although I could probably do an update where you can adjust it if needed. I'll look into it more.
