### ISSUE TITLE
Website/Command Line Option to Add Time

### ISSUE THREAD

**Issue by PXAbstraction** [jamesmontemagno/MyStreamTimer#62]
Hi there! I was wondering if it is possible to use the website or command-line options to add time to an existing timer? I'm looking to use this awesome utility for a challenge idea for my streams where it starts at a certain time and every time I forget to do something, I have to add a minute. I know this can be done with a button but not on a command I could tie to a Stream Deck button. Is this possible or something that could be added?

Thanks for your great work!

**Comment by jamesmontemagno** [comment]
It is on my list that is for sure, should be possible.

**Comment by PXAbstraction** [comment]
Awesome, thank you! :) I mean for now, I can still have my Stream Deck/bot start the timer and can just have the app up and click the "Add Minute" button when needed. So, still doable, just not as streamlined. Cheers!

**Comment by PXAbstraction** [comment]
I just got the update and you addressed everything I wanted to see and the focus stealing issue seems to be fixed too. Thank you so much! I bought the gold tier upgrade. I don't need any of the extra features, but am happy to support small devs doing awesome things. Cheers!

**Comment by jamesmontemagno** [comment]
@PXAbstraction YAY!
