### ISSUE TITLE
Reset the timer while also clearing it

### ISSUE THREAD

**Issue by PXAbstraction** [jamesmontemagno/MyStreamTimer#65]
When you reset a running times, it sets the time back to the start value but leaves it active. So if I had a running timer displaying on my stream and try to reset it, it just goes to the start value and keeps it on screen in perpetuity unless I start like a 1 second timer and let it clear. Is it possible to add in a checkbox option that will just clear the timer when Reset is pressed?

**Comment by jamesmontemagno** [comment]
So... Reset should restart and keep the countdown.

Stop should stop it and clear it out. [will add to backlog].

This is legacy from before we had pause. With pause you can keep the stuff on screen, but agreed that stop should stop and clear.
