### ISSUE TITLE
High CPU Useage

### ISSUE THREAD

**Issue by Whitehat-Nemstar** [jamesmontemagno/MyStreamTimer#69]
9-11% CPU on Core i7 when active counting

Hi,

I'm hitting a constant 10% approx cpu util while My Stream Timer is in use. This seems very high on Windows 10, Core i7, 16Gb RAM, SSD's.

Sean.

**Comment by jamesmontemagno** [comment]
I am actively investigating this right now. Thank you for reporting this.

**Comment by jamesmontemagno** [comment]
Update is rolling out!

**Comment by Whitehat-Nemstar** [comment]
Hi,
Still getting consistently high CPU 8-11% on Windows 10 latest version.

I've tried uninstalling and reinstalling from the Windows Store. Still no improvement.

Has the bug fixed been rolled out?

Thanks

sean.

**Comment by jamesmontemagno** [comment]
What version is it listing?

**Comment by jamesmontemagno** [comment]
Should be version 2.6.x:
![image](https://user-images.githubusercontent.com/1676321/196221358-c5d31e8c-3247-486c-8bf2-06f5216a3b70.png)

Mine hovers around 0
