### ISSUE TITLE
Trying to install using the installer results in an error

### ISSUE THREAD

**Issue by alexxonline** [jamesmontemagno/MyStreamTimer#9]
When i tried to install from https://mystreamtimer.azurewebsites.net/
it says I need to install a certificate first. Tried to  install the certificate provided in the same page but even after installing the certificate I get the same result. Error code 0x800B0109

**Comment by jamesmontemagno** [comment]
That is mostly for demo purposed and i recommend getting form MS store: https://www.microsoft.com/en-us/p/my-stream-timer/9n5nxx3wk7k7

However, you just need to:
Under additional links: 
* download the publisher certificate
* Install -> Local Machine
* Place all certificates in following store: 
* Browse -> Trusted Root Certification Authorities

Then install again
